spring:
    redis:
      jedis:
        ip:
        port:
        auth:
    aop:
        proxy-target-class: true
ad:
  ldapurl: LDAP://lenovo.com
  port: 389
  context_factory: com.sun.jndi.ldap.LdapCtxFactory
  authentication: simple
  userhead: lenovo\\
  basicInfo: sAMAccountName,displayName,msExchExtensionAttribute16,telephoneNumber,mail
  extensionInfo: title,department,physicalDeliveryOfficeName,l,c,mobile,manager,msExchExtensionAttribute16,sAMAccountName,displayName,telephoneNumber
